version: '3'
services:
        web:
                image: cpt_v1
                environment:
                        - CRYPTO_KEY=${CRYPTO_KEY}
                build: .
                ports:
                        - "8041:8041"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
